CREATE TABLE [dbo].[Address]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Country] NVARCHAR(MAX) NOT NULL,
	[City] NVARCHAR(MAX) NOT NULL,
	[Street] NVARCHAR(MAX) NOT NULL,
	[ZipCode] NVARCHAR(MAX) NOT NULL,
	[CreatedAt] DATETIME NOT NULL,
	[DateModify] DATETIME NOT NULL
)
