CREATE TABLE Token(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Title] NVARCHAR(MAX) NOT NULL,
	[Expire] DATETIME NOT NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifyAt] DATETIME NOT NULL
);
CREATE TABLE [Location](
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Country] NVARCHAR(MAX) NOT NULL,
	[City] NVARCHAR(MAX) NOT NULL,
	[Street] NVARCHAR(MAX) NOT NULL,
	[ZipCode] NVARCHAR(MAX) NOT NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifyAt] DATETIME NOT NULL
);
CREATE TABLE Account(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[TokenId] INT FOREIGN KEY REFERENCES Token([Id]),
	[LocationId] INT NULL FOREIGN KEY REFERENCES [Location]([Id]),
	[Email] NVARCHAR(MAX) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifyAt] DATETIME NOT NULL
);
CREATE TABLE Customer(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AccountId] INT FOREIGN KEY REFERENCES Account([Id]),
	[FirstName] NVARCHAR(MAX) NOT NULL,
	[LastName] NVARCHAR(MAX) NOT NULL,
	[Username] NVARCHAR(MAX) NOT NULL,
	[PhoneNumber] NVARCHAR(MAX) NULL,
	[BirthDay] DATETIME NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifyAt] DATETIME NOT NULL
);
CREATE TABLE Court(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AccountId] INT FOREIGN KEY REFERENCES Account([Id]),
	[Name] NVARCHAR(MAX) NOT NULL,
	[WorkingHours] NVARCHAR(MAX) NOT NULL,
	[PriceForHour] NVARCHAR(MAX) NOT NULL,
	[PhoneNumber] NVARCHAR(MAX) NULL,
	[DateOfCreation] DATE NOT NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifyAt] DATETIME NOT NULL
)


-- Customer -> Location